export const $ = selector => (document.querySelector(selector))
export const $$ = selector => (document.querySelectorAll(selector))

export const $BUTTON = $('.click-btn')  
export const $LOTTO_NUMBER_TOGGLE_BUTTON = $('.lotto-numbers-toggle-button')
export const $TICKET_AMOUNT = $('.ticket-amount')
export const $TICKET_UI_WRAP = $('.ticket-UI-wrap')
export const $MONEY_INPUT = $('.money-input')
export const $TICKET_UI = $('.ticketUI')

export const $TICKET_INFO_MODAL = $('.ticket-info-modal')
export const $INPUT_WINNING_NUMBER_MODAL = $('.input-winning-number-modal')
export const $WRAP_MODAL = $('.modal')
export const $INNER_MODAL = $('.modal-inner')
export const $CLOSE_BTN_MODAL = $('.modal-close-btn')
export const $RESTART_BTN_MODAL = $('.restart-btn')
export const $OPEN_RESULT_MODAL = $('.open-result-modal-button')

export const $$WINNING_NUMBER_INPUT_BOX = $$('.winning-number')
export const $BONUS_NUMBER_INPUT_BOX = $('.bonus-number')

export const $COUNT_THREE = $('.count-three')
export const $COUNT_FOUR = $('.count-four')
export const $COUNT_FIVE = $('.count-five')
export const $COUNT_FIVE_BONUS = $('.count-five-bonus')
export const $COUNT_SIX = $('.count-six')

export const $TICKET_NUMBER_INPUT_SECTION = $('.ticket-number-input-section')
export const $LOTTO_COUNT = $('.lotto-count')
export const $$SELF_LOTTO = $$('.self-number')
export const $LOTTO_NUMBER_INPUT_BUTTON = $('.lotto-numbers-input-button')
export const $LOTTO_NUMBER_AUTO_BUTTON = $('.lotto-numbers-auto-button')